### ISSUE TITLE
EOF file issue

### ISSUE THREAD

**Issue by anubhavrohatgi** [AbhishekBose/kafka-cli#1]
```ERROR:root:unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/home/abhishek/anaconda3/lib/python3.6/site-packages/kafka_cli/Kafka/base.py", line 59, in __start_producer
    self.prod_obj.produce(response)
  File "/home/abhishek/anaconda3/lib/python3.6/site-packages/kafka_cli/Kafka/producer.py", line 39, in produce
    updated_msg = eval(msg)
  File "<string>", line 0

**Comment by AbhishekBose** [comment]
Fixed and pushed this. Will be releasing a new build on PyPi after a few more upgrades

**Comment by AbhishekBose** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/abhishek/anaconda3/lib/python3.6/site-packages/kafka_cli/Kafka/base.py", line 59, in __start_producer
>     self.prod_obj.produce(response)
>   File "/home/abhishek/anaconda3/lib/python3.6/site-packages/kafka_cli/Kafka/producer.py", line 39, in produce
>     updated_msg = eval(msg)
>   File "<string>", line 0
>     
> ```

Working on this. Will be releasing the updated version on PyPi soon
